// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace FUNewsManagementSystem.Repository.Models;

public partial class Category
{
    public short CategoryId { get; set; }

    public string CategoryName { get; set; }

    public string CategoryDesciption { get; set; }

    public short? ParentCategoryId { get; set; }

    public bool? IsActive { get; set; }
    [JsonIgnore]
    public virtual ICollection<Category> InverseParentCategory { get; set; } = new List<Category>();
    [JsonIgnore]
    public virtual ICollection<NewsArticleModel> NewsArticles { get; set; } = new List<NewsArticleModel>();

    public virtual Category ParentCategory { get; set; }
}